Metrics/BlockLength:
  ExcludedMethods:
    - 'new'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
